version: 2.1

commands:
  install_nix:
    steps:
      - run: curl https://nixos.org/releases/nix/nix-2.1.2/install | bash -s -- --no-daemon
      - run: echo ". ~/.nix-profile/etc/profile.d/nix.sh" >> ~/.bash_profile
  setup:
    steps:
      - run:
          name: Install common packages
          # direnv: configures environment with .envrc files
          # findutils (where, find, etc): expo-module test
          # git: circleci checkout steps
          # gnugrep: used in .envrc
          # gnutar: used by nix commands which download channels
          # gzip: used by nix commands which download channels
          # openssh: circleci checkout steps
          # rsync: expo-module-scripts uses to copy template files
          # xz: circleci checkout steps
          command: |
            nix-env -iA \
              nixpkgs.direnv \
              nixpkgs.findutils \
              nixpkgs.git \
              nixpkgs.gnugrep \
              nixpkgs.gnutar \
              nixpkgs.gzip \
              nixpkgs.openssh \
              nixpkgs.rsync \
              nixpkgs.xz
      - run: mkdir -p ~/.config/direnv
      - run: echo -e "[whitelist]\nprefix = [ \"$HOME\" ]" > ~/.config/direnv/config.toml
      - run: echo 'eval "$(direnv export bash)"' >> ~/.bash_profile
      - run: echo '--frozen-lockfile true' >> ~/.yarnrc
      - checkout
  decrypt_secrets_if_possible:
    steps:
      - run: |
          if ! [ -v EXPO_GIT_CRYPT_KEY_BASE64 ]; then
            echo 'git-crypt key not present in environment' && exit 0
          fi
          git crypt unlock <(echo $EXPO_GIT_CRYPT_KEY_BASE64 | base64 --decode)
  update_submodules:
    steps:
      - run: git submodule update --init
  fetch_cocoapods_specs:
    steps:
      - run: curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
  restore_yarn_cache:
    parameters:
      working_directory:
        type: string
        default: .
    steps:
      - restore_cache:
          key: yarn-v1-{{ checksum "<< parameters.working_directory >>/yarn.lock" }}
  save_yarn_cache:
    parameters:
      working_directory:
        type: string
        default: .
    steps:
      - save_cache:
          key: yarn-v1-{{ checksum "<< parameters.working_directory >>/yarn.lock" }}
          paths:
            - ~/.cache/yarn # `yarn cache dir`
  restore_gradle_cache:
    steps:
      - restore_cache:
          key: jars-v1-{{ checksum "android/build.gradle" }}-{{ checksum "android/app/build.gradle" }}
  save_gradle_cache:
    steps:
      - save_cache:
          key: jars-v1-{{ checksum "android/build.gradle" }}-{{ checksum "android/app/build.gradle" }}
          paths:
            - ~/.gradle
  yarn:
    parameters:
      command:
        type: string
        default: install
      working_directory:
        type: string
      max_tries:
        type: integer
        default: 1
    steps:
      - run:
          name: yarn << parameters.command >> (<< parameters.working_directory >>)
          working_directory: << parameters.working_directory >>
          command: for i in {1..<< parameters.max_tries >>}; do ((i > 1)) && sleep 5; yarn << parameters.command >> && break; done
  yarn_install:
    parameters:
      working_directory:
        type: string
    steps:
      - yarn:
          command: 'install'
          working_directory: << parameters.working_directory >>
          max_tries: 5

executors:
  # We add -l to all the shell commands to make it easier to use direnv
  nix: &nix
    docker:
      - image: lnl7/nix:2.1.2
    # Symlink to the readline-enabled bash which is the default command of the container
    shell: /run/current-system/sw/bin/bash -leo pipefail
    working_directory: ~/expo
    environment:
      # fastlane complains if these are not set
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      FASTLANE_SKIP_UPDATE_CHECK: 1
      FASTLANE_DISABLE_COLORS: 1
      CI: 1
  android:
    <<: *nix
    resource_class: xlarge
  js:
    <<: *nix
    resource_class: small
  web:
    docker:
      - image: circleci/node:latest-browsers
    shell: /bin/bash -leo pipefail
    working_directory: ~/expo
    resource_class: small
    environment:
      USER: circleci
  mac:
    macos: # https://circleci.com/docs/2.0/testing-ios/#supported-xcode-versions
      xcode: '10.1.0'
    working_directory: /Users/distiller/project
    shell: /bin/bash -leo pipefail
    environment:
      # fastlane complains if these are not set
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      FASTLANE_SKIP_UPDATE_CHECK: 1
      FASTLANE_DISABLE_COLORS: 1
      CI: 1

workflows:
  docs:
    jobs:
      - docs
      - docs_approve_deploy:
          type: approval
          requires:
            - docs
          filters:
            branches:
              only:
                - master
                - /.*all-ci.*/
      - docs_deploy:
          requires:
            - docs_approve_deploy

  # JavaScript packages that make up the SDK
  sdk:
    jobs:
      - expo_sdk
      - web_test_suite
      - web_storybook
      - babel_preset

  # Android and iOS clients
  client:
    jobs:
      - home
      - expotools
      - client_android
      - client_ios
      - test_suite_publish
      - android_test_suite:
          requires:
            - test_suite_publish
      - client_android_approve_google_play:
          type: approval
          requires:
            - client_android
          filters:
            branches:
              only:
                - /sdk-\d+/
                - /.*all-ci.*/
      - client_android_release_google_play:
          requires:
            - client_android_approve_google_play
  #     - shell_app_ios_tests:
  #         requires:
  #           - shell_app_sim_base_ios
  #           - test_suite_publish

  shell_app:
    jobs:
      - shell_app_ios_approve_build:
          type: approval
          filters:
            branches:
              only:
                - /sdk-\d+/
                - /.*all-ci.*/
      - shell_app_ios_build:
          requires:
            - shell_app_ios_approve_build
      - shell_app_android_approve_build:
          type: approval
          filters:
            branches:
              only:
                - /sdk-\d+/
                - /.*all-ci.*/
      - shell_app_android_build:
          requires:
            - shell_app_android_approve_build

  client_shell_app:
    jobs:
      - expo_client_approve_build:
          type: approval
          filters:
            branches:
              only:
                - /sdk-\d+/
                - /.*all-ci.*/
      - expo_client_build:
          requires:
            - expo_client_approve_build

jobs:
  expo_sdk:
    executor: js
    steps:
      - setup
      - update_submodules
      - restore_yarn_cache
      - yarn_install:
          working_directory: ~/expo
      - save_yarn_cache
      # Add back linting once we get ESLint or TSLint set up
      - run: expotools check-packages

  web_test_suite:
    executor: web
    steps:
      - install_nix
      - setup
      - update_submodules
      - restore_yarn_cache
      - yarn_install:
          working_directory: ~/expo
      - save_yarn_cache
      - yarn:
          command: test:web:ci
          working_directory: ~/expo/apps/test-suite

  web_storybook:
    executor: web
    steps:
      - install_nix
      - setup
      - update_submodules
      - restore_yarn_cache
      - yarn_install:
          working_directory: ~/expo
      - save_yarn_cache
      - yarn:
          command: test:web:ci
          working_directory: ~/expo/apps/storybook

  babel_preset:
    executor: js
    steps:
      - setup
      - update_submodules
      - restore_yarn_cache
      - yarn_install:
          working_directory: ~/expo
      - save_yarn_cache
      - yarn:
          command: lint --max-warnings 0
          working_directory: ~/expo/packages/babel-preset-expo
      - yarn:
          command: jest --maxWorkers 1
          working_directory: ~/expo/packages/babel-preset-expo

  home:
    executor: js
    steps:
      - setup
      - update_submodules
      - restore_yarn_cache
      - yarn_install:
          working_directory: ~/expo
      - save_yarn_cache
      - yarn:
          command: jest --maxWorkers 1
          working_directory: ~/expo/home

  expotools:
    executor: js
    steps:
      - setup
      - restore_yarn_cache:
          working_directory: ~/expo/tools/expotools
      - yarn_install:
          working_directory: ~/expo/tools/expotools
      - save_yarn_cache:
          working_directory: ~/expo/tools/expotools
      - yarn:
          command: tsc
          working_directory: ~/expo/tools/expotools

  client_ios:
    executor: mac
    steps:
      - install_nix
      - setup
      - update_submodules
      - run: git lfs pull
      - fetch_cocoapods_specs
      - run: nix run expo.procps --command fastlane ios create_simulator_build
      - store_artifacts:
          path: ~/Library/Logs/fastlane/

  expo_client_build:
    executor: mac
    steps:
      - install_nix
      - setup
      - update_submodules
      - run: git lfs pull
      - fetch_cocoapods_specs
      - run:
          name: Build Expo Client and upload tarball
          command: |
            export TARBALL=ios-expo-client-$CIRCLE_SHA1.tar.gz
            fastlane ios create_expo_client_build
            tar \
              -C ~/project \
              -zcf "/tmp/$TARBALL" \
              expo-client-build/Exponent.xcarchive \
              ios
            ~/project/bin/aws s3 cp --acl public-read "/tmp/$TARBALL" s3://exp-artifacts
      - run:
          name: Expo Client shell app url
          command: echo "Expo Client shell app tarball uploaded to s3://exp-artifacts/ios-expo-client-$CIRCLE_SHA1.tar.gz"

  shell_app_ios_build:
    executor: mac
    steps:
      - install_nix
      - setup
      - update_submodules
      - run: git lfs pull
      - fetch_cocoapods_specs
      - yarn_install:
          working_directory: ~/project/tools-public
      - run: et ios-generate-dynamic-macros
      - run: echo "--run.cwd project/tools-public" >> ~/.yarnrc
      - run:
          name: Build iOS shell app for real devices
          working_directory: ~/project/tools-public
          no_output_timeout: 30m
          command: nix run expo.procps --command gulp ios-shell-app --action build --type archive --verbose true --skipRepoUpdate --shellAppSdkVersion UNVERSIONED
      - run:
          name: Build iOS shell app for simulators
          working_directory: ~/project/tools-public
          no_output_timeout: 30m
          command: nix run expo.procps --command gulp ios-shell-app --action build --type simulator --verbose true --skipRepoUpdate --shellAppSdkVersion UNVERSIONED
      - run:
          name: Package and upload release tarball
          working_directory: ~/project
          no_output_timeout: 40m
          command: |
              export TARBALL=ios-shell-builder-sdk-latest-$CIRCLE_SHA1.tar.gz
              tar \
                -zcf "/tmp/$TARBALL" \
                package.json \
                exponent-view-template \
                shellAppBase-builds \
                shellAppWorkspaces \
                ios
              ~/project/bin/aws s3 cp --acl public-read "/tmp/$TARBALL" s3://exp-artifacts
              echo "Release tarball uploaded to s3://exp-artifacts/$TARBALL"
              echo "You can deploy this in Terraform by setting commit to $CIRCLE_SHA1"

  shell_app_android_build:
    executor: android
    steps:
      - setup
      - run: echo 'export S3_URI=s3://exp-artifacts/android-shell-builder-$CIRCLE_SHA1.tar.gz' >> $BASH_ENV
      - decrypt_secrets_if_possible
      - yarn_install:
          working_directory: ~/expo/tools-public
      - yarn_install:
          working_directory: ~/expo/tools
      - run: |
          aws s3 ls $S3_URI || {
            ./buildAndroidTarballLocally.sh # TODO: put in fastlane?
            aws s3 cp --acl public-read artifacts/android-shell-builder.tar.gz $S3_URI
          }

  android_test_suite:
    executor: android
    steps:
      - setup
      - update_submodules
      - yarn_install:
          working_directory: ~/expo # need jsc-android dependency in expokit-npm-package
      - yarn_install:
          working_directory: ~/expo/tools-public
      - restore_gradle_cache
      - run: |
          nix-shell android/shell.nix --pure \
            --keep AWS_ACCESS_KEY_ID \
            --keep AWS_SECRET_ACCESS_KEY \
            --keep SSL_CERT_FILE \
            --keep FASTLANE_SKIP_UPDATE_CHECK \
            --keep FASTLANE_DISABLE_COLORS \
            --keep CI \
            --run "fastlane android devicefarm"
      - save_gradle_cache

  client_android:
    executor: android
    steps:
      - setup
      - update_submodules
      - yarn_install:
          working_directory: ~/expo # need jsc-android dependency in expokit-npm-package
      - yarn_install:
          working_directory: ~/expo/tools-public
      - restore_gradle_cache
      - decrypt_secrets_if_possible
      - run: echo $ANDROID_KEYSTORE_B64 | base64 -d > android/app/release-key.jks
      - run: |
          nix-shell android/shell.nix --pure \
            --keep ANDROID_KEYSTORE_PASSWORD \
            --keep ANDROID_KEY_ALIAS \
            --keep ANDROID_KEY_PASSWORD \
            --keep FASTLANE_SKIP_UPDATE_CHECK \
            --keep FASTLANE_DISABLE_COLORS \
            --keep CI \
            --run "fastlane android build build_type:Release"
      - save_gradle_cache
      - save_cache:
          key: client-android-apk-{{ .Revision }}
          paths:
            - ~/expo/android/app/build/outputs/apk
      - store_artifacts:
          path: ~/expo/android/app/build/outputs/apk
      - store_artifacts: # daemon logs for debugging crashes
          path: ~/.gradle/daemon

  client_android_release_google_play:
    executor: js
    steps:
      - setup
      - restore_cache:
          key: client-android-apk-{{ .Revision }}
      - run: echo $ANDROID_KEYSTORE_B64 | base64 -d > android/app/release-key.jks
      - run:
          name: Upload APK to Google Play and release to production
          working_directory: ~/expo
          command: fastlane android prod_release

  docs:
    executor: nix
    resource_class: xlarge # TODO: Use less than 8Gib of ram to build a static site
    steps:
      - setup
      - update_submodules
      - yarn_install:
          working_directory: docs
      - yarn:
          command: export
          working_directory: docs
      - run:
          working_directory: docs
          command: yarn run export-server
          background: true
      - run:
          working_directory: docs
          command: nix run expo.curl --command yarn run test-links http://localhost:8000
      - save_cache:
          key: docs-site-{{ .Revision }}
          paths:
            - docs/out

  docs_deploy:
    executor: nix
    steps:
      - setup
      - restore_cache:
          keys:
            - docs-site-{{ .Revision }}
      - deploy:
          command: ./deploy.sh
          working_directory: docs

  test_suite_publish:
    executor: nix
    steps:
      - setup
      - update_submodules
      - decrypt_secrets_if_possible
      - run:
          working_directory: ~/expo/apps/test-suite
          command: ./publish.sh
